[build] 
  publish = "dist"
  functions = "src/functions"
  command = "npm run build"

[dev] 
  publish = "dist"
  functions = "src/functions"
  command = "eleventy --serve"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

